# Generated by Django 4.0.3 on 2024-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno hráče musí být vyplněno'}, help_text='Zadejte jméno hráče', max_length=80, verbose_name='Jméno hráče')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení hráče musí být vyplněno'}, help_text='Zadejte příjmení hráče', max_length=50, verbose_name='Příjmení hráče')),
                ('goly', models.IntegerField(error_messages={'blank': 'Počet golů musí být vyplněný'}, help_text='Zadejte počet golů', verbose_name='Počet golů')),
                ('asistence', models.IntegerField(error_messages={'blank': 'Počet asistencí musí být vyplněný'}, help_text='Zadejte počet asistencí', verbose_name='Počet asistencí')),
                ('pocet_zapasu', models.IntegerField(error_messages={'blank': 'Počet zápasů musí být vyplněný'}, help_text='Zadejte počet zápasů', verbose_name='Počet zápasů')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_liga', models.CharField(error_messages={'blank': 'Název ligy musí být vyplněno'}, help_text='Zadejte název ligy', max_length=80, verbose_name='Název ligy')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligy',
                'ordering': ['nazev_liga'],
            },
        ),
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_tymu', models.CharField(error_messages={'blank': 'Název týmu musí být vyplněno'}, help_text='Zadejte název týmu', max_length=80, verbose_name='Název týmu')),
                ('goly', models.IntegerField(error_messages={'blank': 'Počet golů musí být vyplněný'}, help_text='Zadejte počet golů', verbose_name='Počet golů')),
                ('vyhry', models.IntegerField(error_messages={'blank': 'Počet výher musí být vyplněný'}, help_text='Zadejte počet výher', verbose_name='Počet výher')),
                ('prohry', models.IntegerField(error_messages={'blank': 'Počet proher musí být vyplněný'}, help_text='Zadejte počet proher', verbose_name='Počet proher')),
                ('remizy', models.IntegerField(error_messages={'blank': 'Počet remíz musí být vyplněný'}, help_text='Zadejte počet remízy', verbose_name='Počet remízy')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
                'ordering': ['nazev_tymu', 'goly', 'vyhry', 'prohry', 'remizy'],
            },
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_zapasu', models.DateField(error_messages={'blank': 'Datum zápasu musí být vyplněný'}, help_text='Zadejte datum zápasu', verbose_name='Datum zápasu')),
                ('domaci_tym', models.CharField(error_messages={'blank': 'Název týmu musí být vyplněný'}, help_text='Zadejte název týmu', max_length=80, verbose_name='Název týmu')),
                ('hostujici_tym', models.CharField(error_messages={'blank': 'Název týmu musí být vyplněný'}, help_text='Zadejte název týmu', max_length=80, verbose_name='Název týmu')),
                ('skore_domaci_tym', models.IntegerField(error_messages={'blank': 'Počet golů domácích musí být vyplněný'}, help_text='Zadejte počet golů domácích', verbose_name='Počet golů domácích')),
                ('skore_hostujici_tym', models.IntegerField(error_messages={'blank': 'Počet golů hostů musí být vyplněný'}, help_text='Zadejte počet golů hostů', verbose_name='Počet golů hostů')),
            ],
            options={
                'verbose_name': 'Zápas',
                'verbose_name_plural': 'Zápasy',
                'ordering': ['domaci_tym', 'hostujici_tym'],
            },
        ),
    ]
